server:
  port: 8805
spring:
  application:
    name: myspringcloud-order
    cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          service-name: myspringcloud-order
      profiles:
        active: dev

